#!/usr/bin/env python3

#
# EPITECH PROJECT, 2024
# GomokuAI
# File description:
# pbrain-gomoku-ai
#

from models.Board import Board

def main():
    board = Board()

    board.display_board()

if __name__ == '__main__':
    main()
